# Generated by Django 4.2.17 on 2026-09-07 20:12

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_order_items_remove_order_total_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=marketplace.models.generate_sku, max_length=50, unique=True),
        ),
    ]
