# Generated by Django 4.2.27 on 2026-01-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
