# Generated by Django 4.2.27 on 2026-01-17 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-subscribed_date'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
