# Generated by Django 4.2.27 on 2026-01-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_service_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='related_work',
            field=models.CharField(choices=[('farmer_api_key', 'Farmer API Key Request'), ('crop_disease_api', 'Crop Disease Prediction API'), ('soil_analysis', 'AI Soil Analysis'), ('weather_forecast', 'Weather Forecast Integration'), ('smart_irrigation', 'Smart Irrigation System'), ('dashboard_access', 'Agriculture Dashboard Access'), ('model_training', 'Model Training / Custom AI Model'), ('technical_support', 'Technical Support'), ('partnership', 'Partnership / Collaboration'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
