# Generated by Django 4.2.27 on 2026-01-23 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_related_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodegradableCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('materials_accepted', models.TextField(help_text='Comma-separated list of materials accepted')),
                ('benefits_offered', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('waste_type', models.CharField(choices=[('stubble', 'Stubble'), ('damaged_crop', 'Damaged Crop'), ('husks', 'Husks'), ('biomass', 'Biomass'), ('other', 'Other')], max_length=20)),
                ('quantity', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_submissions/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
