# Generated by Django 4.2.17 on 2026-09-08 18:22

from django.db import migrations


def migrate_phone_numbers(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    try:
        AgroProfile = apps.get_model('agrolease', 'AgroProfile')
    except LookupError:
        AgroProfile = None

    for user in User.objects.all():
        profile, _ = UserProfile.objects.get_or_create(user=user)
        if AgroProfile:
            try:
                agro_profile = AgroProfile.objects.get(user=user)
                if agro_profile.phone_number:
                    profile.phone_number = agro_profile.phone_number
                    profile.is_phone_verified = True  # Assuming existing users were verified
                    profile.save()
            except AgroProfile.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('agrolease', '0005_land_rejected_status'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers, reverse_code=migrations.RunPython.noop),
    ]
