# Generated by Django 4.2.27 on 2026-01-16 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio for the author')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('website', models.URLField(blank=True, help_text='Personal website URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
