"""
Site-wide pages and crawler files.

Holds the legal pages every public site needs, plus robots.txt. The sitemap
itself is generated by django.contrib.sitemaps (see core/sitemaps.py).
"""

from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_GET


@require_GET
def privacy_policy(request):
    return render(request, 'core/privacy_policy.html')


@require_GET
def terms_and_conditions(request):
    return render(request, 'core/terms_and_conditions.html')


@require_GET
@cache_control(max_age=60 * 60 * 24)
def robots_txt(request):
    """
    Serve robots.txt from the app rather than as a static file, so the Sitemap
    line always points at the host actually being used instead of a hardcoded
    domain that breaks on staging.

    Crawlers are kept out of anything authenticated, anything that triggers an
    expensive model inference, and the device ingest API.
    """
    sitemap_url = request.build_absolute_uri(reverse('core:sitemap'))
    lines = [
        'User-agent: *',
        '',
        '# Private / authenticated areas',
        'Disallow: /admin/',
        'Disallow: /accounts/',
        'Disallow: /agrolease/',
        'Disallow: /iot/',
        '',
        '# Expensive or stateful endpoints - no crawl value',
        'Disallow: /detection/api/',
        'Disallow: /detection/chatbot/',
        'Disallow: /detection/history/',
        'Disallow: /marketplace/cart/',
        'Disallow: /marketplace/checkout/',
        '',
        '# Media uploads include farmer KYC documents and field photos',
        'Disallow: /media/verification/',
        'Disallow: /media/rejected/',
        '',
        'Allow: /',
        '',
        f'Sitemap: {sitemap_url}',
    ]
    return HttpResponse('\n'.join(lines) + '\n', content_type='text/plain; charset=utf-8')
