# Generated by Django 4.2.27 on 2026-01-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Name of the crop', max_length=100)),
                ('crop_image', models.ImageField(help_text='Image of the crop', upload_to='market_prices/')),
                ('category', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Pulses', 'Pulses'), ('Other', 'Other')], help_text='Category of the crop', max_length=50)),
                ('market_location', models.CharField(help_text='Location of the market', max_length=100)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, help_text='Price per quintal in rupees', max_digits=10)),
                ('price_unit', models.CharField(default='₹ / Quintal', help_text='Unit of price', max_length=20)),
                ('price_trend', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down'), ('Stable', 'Stable')], help_text='Trend of the price', max_length=10)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Quality grade (optional)', max_length=1, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes or description', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Is this price active?')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-last_updated'],
            },
        ),
    ]
