# Generated by Django 4.2.27 on 2026-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Crop name', max_length=100)),
                ('crop_image', models.ImageField(help_text='Crop image', upload_to='crop_info/')),
                ('category', models.CharField(choices=[('Cereals', 'Cereals'), ('Pulses', 'Pulses'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Oilseeds', 'Oilseeds'), ('Spices', 'Spices')], max_length=50)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Zaid', 'Zaid')], max_length=20)),
                ('soil_type', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('sowing_time', models.CharField(max_length=100)),
                ('harvesting_time', models.CharField(max_length=100)),
                ('water_requirement', models.CharField(max_length=100)),
                ('fertilizer_requirement', models.TextField()),
                ('common_diseases', models.TextField()),
                ('prevention_tips', models.TextField()),
                ('average_yield', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop Information',
                'verbose_name_plural': 'Crop Information',
                'ordering': ['crop_name'],
            },
        ),
    ]
