# Generated by Django 4.2.27 on 2026-01-18 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_cropinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scheme Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ministry', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget in Crore Rupees', max_digits=15)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('application_process', models.TextField()),
                ('fiscal_year', models.CharField(default='FY2025-26', max_length=20)),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(default='fas fa-seedling', help_text='FontAwesome icon class', max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('documents_required', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='features.schemecategory')),
            ],
            options={
                'ordering': ['-last_updated', 'name'],
                'indexes': [models.Index(fields=['name', 'ministry'], name='features_go_name_3d5f0b_idx'), models.Index(fields=['category', 'is_active'], name='features_go_categor_659c8d_idx')],
            },
        ),
    ]
