# Generated by Django 4.2.27 on 2026-01-22 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0003_schemecategory_governmentscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the suggestion', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the suggestion')),
                ('category', models.CharField(choices=[('General', 'General'), ('Urgent', 'Urgent'), ('Seasonal', 'Seasonal'), ('Crop-specific', 'Crop-specific')], default='General', help_text='Category of the suggestion', max_length=20)),
                ('crop', models.CharField(blank=True, help_text='Specific crop if applicable', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this suggestion active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content')),
                ('is_from_admin', models.BooleanField(default=False, help_text='Is this message from admin?')),
                ('is_read', models.BooleanField(default=False, help_text='Has this message been read?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Message timestamp')),
                ('user', models.ForeignKey(help_text='Farmer who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
