# Generated by Django 4.2.17 on 2026-10-06 03:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='bi-leaf', help_text='A Bootstrap Icons class, e.g. bi-leaf, bi-cpu, bi-droplet.', max_length=60)),
                ('link_label', models.CharField(blank=True, max_length=60)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage feature card',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, help_text='One or two short sentences. Keep it readable on a phone.')),
                ('image', models.ImageField(blank=True, help_text='Wide image, around 1920x1080. Large uploads are compressed automatically.', null=True, upload_to='site/hero/')),
                ('image_alt', models.CharField(blank=True, help_text='Describes the image for screen readers and when images fail to load.', max_length=160)),
                ('cta_label', models.CharField(blank=True, default='Scan your crop free', help_text='Button text. Blank hides the button.', max_length=60)),
                ('cta_url', models.CharField(blank=True, default='/detection/diagnosis/', help_text='Where the button goes. A path like /detection/diagnosis/ or a full URL.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Homepage hero slide',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AI Crop Health', help_text='Shown in the browser tab, link previews and the admin header.', max_length=100)),
                ('tagline', models.CharField(default='AI crop disease diagnosis, land leasing and IoT field monitoring for farmers', help_text='Used as the default meta description and link-preview text.', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Header logo. Leave blank to use the bundled default.', null=True, upload_to='site/')),
                ('social_preview_image', models.ImageField(blank=True, help_text='Shown when a link is shared on WhatsApp/Facebook/X. 1200x630 works best.', null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits with country code, no +. Example: 919876543210', max_length=30)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('analytics_script_url', models.URLField(blank=True, help_text='Cookieless analytics script, e.g. https://plausible.io/js/script.js. Blank disables analytics. Only loaded after the visitor consents.')),
                ('analytics_site_id', models.CharField(blank=True, max_length=120)),
                ('enable_marketplace', models.BooleanField(default=True)),
                ('enable_iot', models.BooleanField(default=True, verbose_name='Enable IoT sensors')),
                ('enable_chatbot', models.BooleanField(default=True)),
                ('enable_agrolease', models.BooleanField(default=True, verbose_name='Enable land leasing')),
                ('enable_registration', models.BooleanField(default=True, help_text='Uncheck to stop new sign-ups without taking the site down.')),
                ('diagnosis_confidence_threshold', models.FloatField(default=97.0, help_text='A prediction below this confidence is flagged to the farmer as unreliable. This is NOT a measure of model accuracy.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('diagnosis_disclaimer', models.TextField(default='This diagnosis is advisory and can be wrong. Confirm with a qualified agronomist before treating or destroying a crop.', help_text='Shown with every diagnosis result.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Shows a maintenance notice to visitors. Staff can still browse.')),
                ('maintenance_message', models.TextField(blank=True, default='We are carrying out scheduled maintenance. Please check back shortly.')),
                ('announcement', models.CharField(blank=True, help_text='Optional banner shown at the top of every page. Blank hides it.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
