# Generated by Django 4.2.17 on 2026-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featurecard_heroslide_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
    ]
