# Generated by Django 4.2.27 on 2026-01-21 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uploaded_image', models.ImageField(null=True, upload_to='diagnoses/%Y/%m/%d/')),
                ('image_resolution', models.CharField(max_length=20)),
                ('image_size_kb', models.IntegerField()),
                ('quality_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sharpness_score', models.FloatField(null=True)),
                ('brightness_score', models.FloatField(null=True)),
                ('passed_quality_check', models.BooleanField(default=False)),
                ('quality_failure_reason', models.TextField(blank=True, null=True)),
                ('predicted_crop', models.CharField(max_length=100)),
                ('predicted_disease', models.CharField(max_length=200)),
                ('class_index', models.IntegerField()),
                ('class_label', models.CharField(max_length=200)),
                ('raw_confidence', models.FloatField(help_text='Raw TFLite model confidence', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calibrated_confidence', models.FloatField(help_text='After temperature scaling and entropy adjustment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entropy_score', models.FloatField(blank=True, null=True)),
                ('diagnosis_status', models.CharField(choices=[('highly_reliable', 'Highly Reliable (≥98%)'), ('moderate_confidence', 'Moderate Confidence (95-97%)'), ('unreliable', 'Unreliable (<95%)')], max_length=30)),
                ('used_gemini_validation', models.BooleanField(default=False)),
                ('gemini_confidence', models.FloatField(blank=True, null=True)),
                ('gemini_recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('gemini_concerns', models.JSONField(blank=True, null=True)),
                ('solutions_shown', models.BooleanField(default=False)),
                ('warning_message', models.TextField(blank=True, null=True)),
                ('farmer_confirmed', models.BooleanField(blank=True, null=True)),
                ('farmer_feedback', models.TextField(blank=True, null=True)),
                ('farmer_feedback_date', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_false_positive', models.BooleanField(blank=True, null=True)),
                ('correct_diagnosis', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QualityRejectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_image', models.ImageField(upload_to='rejected/%Y/%m/%d/')),
                ('rejection_reasons', models.JSONField()),
                ('image_resolution', models.CharField(max_length=20)),
                ('sharpness_score', models.FloatField(null=True)),
                ('brightness_score', models.FloatField(null=True)),
                ('quality_score', models.FloatField()),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FarmerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_correct', models.BooleanField(help_text='Did the diagnosis match field symptoms?')),
                ('treatment_worked', models.BooleanField(blank=True, help_text='Did recommended treatment work?', null=True)),
                ('actual_disease', models.CharField(blank=True, help_text='What was the actual disease (if different)?', max_length=200, null=True)),
                ('comments', models.TextField(blank=True)),
                ('farmer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('farmer_location', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnosis_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detection.diagnosislog')),
            ],
            options={
                'ordering': ['-feedback_date'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosislog',
            index=models.Index(fields=['-timestamp'], name='detection_d_timesta_dde709_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosislog',
            index=models.Index(fields=['diagnosis_status'], name='detection_d_diagnos_49d82b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosislog',
            index=models.Index(fields=['predicted_crop', 'predicted_disease'], name='detection_d_predict_ce4ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosislog',
            index=models.Index(fields=['calibrated_confidence'], name='detection_d_calibra_189f4f_idx'),
        ),
    ]
