# Generated by Django 4.2.27 on 2026-01-22 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('weather', 'Weather Alert'), ('pest', 'Pest Outbreak'), ('market', 'Market Update'), ('disease', 'Disease Outbreak'), ('advisory', 'General Advisory')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', help_text='Critical alerts appear first', max_length=10)),
                ('title', models.CharField(help_text="Alert headline (e.g., 'Heavy Rainfall Expected This Week')", max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message with actionable advice')),
                ('affected_crops', models.CharField(blank=True, help_text="Comma-separated crop names (e.g., 'Rice, Wheat, Cotton')", max_length=300)),
                ('is_global', models.BooleanField(db_index=True, default=False, help_text='Show to all users regardless of location')),
                ('applicable_locations', models.TextField(blank=True, help_text='Comma-separated locations. Leave empty if global.')),
                ('applicable_soil_types', models.CharField(default='any', help_text="Comma-separated soil types or 'any'", max_length=200)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When alert becomes active')),
                ('valid_until', models.DateTimeField(help_text='Alert expires after this date')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned alerts always appear at top')),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Agriculture Alert',
                'verbose_name_plural': 'Agriculture Alerts',
                'ordering': ['-is_pinned', '-severity', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='AgricultureSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Clear, actionable title (e.g., 'Plant Drought-Resistant Crops')", max_length=200)),
                ('category', models.CharField(choices=[('crop', 'Crop Management'), ('weather', 'Weather Advisory'), ('soil', 'Soil Health'), ('fertilizer', 'Fertilizer Recommendation'), ('pest', 'Pest Control'), ('market', 'Market Intelligence')], db_index=True, max_length=20)),
                ('description', models.TextField(help_text='Detailed recommendation with specific actions')),
                ('is_global', models.BooleanField(db_index=True, default=False, help_text='Show to all users regardless of location')),
                ('applicable_locations', models.TextField(blank=True, help_text="Comma-separated locations (e.g., 'Maharashtra, Karnataka, Punjab'). Leave empty if global.")),
                ('applicable_soil_types', models.CharField(default='any', help_text="Comma-separated soil types (e.g., 'loamy,clay') or 'any' for all", max_length=200)),
                ('applicable_seasons', models.CharField(default='all', help_text="Comma-separated seasons (e.g., 'monsoon,winter') or 'all' for all seasons", max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], db_index=True, default='medium', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive suggestions are hidden from users')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this suggestion becomes visible')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional: Auto-hide after this date', null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Agriculture Suggestion',
                'verbose_name_plural': 'Agriculture Suggestions',
                'ordering': ['-priority', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('helpful', '👍 Helpful'), ('not_helpful', '👎 Not Helpful'), ('viewed', '👁 Viewed')], max_length=20)),
                ('session_id', models.CharField(max_length=100)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_location', models.CharField(max_length=100)),
                ('user_soil_type', models.CharField(max_length=50)),
                ('user_season', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='detection.agriculturealert')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='detection.agriculturesuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key_provided', models.CharField(blank=True, max_length=100)),
                ('is_valid_key', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('http_status', models.IntegerField()),
                ('suggestions_count', models.IntegerField(default=0)),
                ('alerts_count', models.IntegerField(default=0)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='detection_a_timesta_816567_idx'), models.Index(fields=['is_valid_key'], name='detection_a_is_vali_7e6425_idx'), models.Index(fields=['http_status'], name='detection_a_http_st_7ec7bf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agriculturesuggestion',
            index=models.Index(fields=['is_active', 'publish_date'], name='detection_a_is_acti_b65d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='agriculturesuggestion',
            index=models.Index(fields=['category', 'priority'], name='detection_a_categor_f1ec98_idx'),
        ),
        migrations.AddIndex(
            model_name='agriculturesuggestion',
            index=models.Index(fields=['is_global'], name='detection_a_is_glob_d9717c_idx'),
        ),
        migrations.AddIndex(
            model_name='agriculturealert',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='detection_a_is_acti_979f56_idx'),
        ),
        migrations.AddIndex(
            model_name='agriculturealert',
            index=models.Index(fields=['severity', 'alert_type'], name='detection_a_severit_5780ad_idx'),
        ),
        migrations.AddIndex(
            model_name='agriculturealert',
            index=models.Index(fields=['is_global'], name='detection_a_is_glob_478934_idx'),
        ),
        migrations.AddIndex(
            model_name='agriculturealert',
            index=models.Index(fields=['is_pinned'], name='detection_a_is_pinn_45f9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userreaction',
            index=models.Index(fields=['suggestion', 'reaction_type'], name='detection_u_suggest_8f0c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='userreaction',
            index=models.Index(fields=['alert', 'reaction_type'], name='detection_u_alert_i_0defc8_idx'),
        ),
        migrations.AddIndex(
            model_name='userreaction',
            index=models.Index(fields=['session_id'], name='detection_u_session_82c328_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userreaction',
            unique_together={('suggestion', 'session_id', 'reaction_type'), ('alert', 'session_id', 'reaction_type')},
        ),
    ]
