# Generated by Django 4.2.27 on 2026-01-22 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_agriculturealert_agriculturesuggestion_userreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosislog',
            name='brightness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosislog',
            name='calibrated_confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='diagnosislog',
            name='diagnosis_status',
            field=models.CharField(choices=[('highly_reliable', 'Highly Reliable (≥98%)'), ('moderate_confidence', 'Moderate Confidence (95–97%)'), ('unreliable', 'Unreliable (<95%)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='diagnosislog',
            name='raw_confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='diagnosislog',
            name='sharpness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosislog',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='diagnoses/%Y/%m/%d/'),
        ),
    ]
