# Generated by Django 4.2.17 on 2026-09-08 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0003_alter_diagnosislog_brightness_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosis_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_histories', to='detection.diagnosislog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detection Histories',
                'ordering': ['-saved_at'],
            },
        ),
    ]
