# Generated by Django 4.2.17 on 2026-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_diagnosislog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosislog',
            name='fallback_reason',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='diagnosislog',
            name='provider',
            field=models.CharField(choices=[('crop.health', 'crop.health API'), ('local', 'Bundled PlantVillage model')], db_index=True, default='local', max_length=30),
        ),
        migrations.AlterField(
            model_name='diagnosislog',
            name='diagnosis_status',
            field=models.CharField(choices=[('reliable', 'Reliable - treatment shown'), ('caution', 'Needs confirmation - treatment withheld'), ('unreliable', 'Not confident - treatment withheld'), ('not_a_plant', 'No plant detected')], max_length=30),
        ),
    ]
