# Generated by Django 4.2.17 on 2026-10-06 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0006_diagnosislog_fallback_reason_diagnosislog_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='detection.diagnosislog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Farmer'), ('assistant', 'AI')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('preset', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('treatment_gated', models.BooleanField(default=False)),
                ('flagged_by_admin', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='detection.diagnosisconversation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='detection_d_convers_2e345a_idx'), models.Index(fields=['-created_at'], name='detection_d_created_f87186_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosisconversation',
            index=models.Index(fields=['-created_at'], name='detection_d_created_e98733_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisconversation',
            index=models.Index(fields=['diagnosis_log', '-created_at'], name='detection_d_diagnos_cb9ad5_idx'),
        ),
    ]
