# Generated by Django 4.2.17 on 2026-10-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_diagnosisconversation_diagnosismessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosismessage',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
