# Generated by Django 4.2.17 on 2026-10-06 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0008_alter_diagnosismessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsectIdentificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='insects/%Y/%m/%d/')),
                ('image_resolution', models.CharField(blank=True, default='', max_length=20)),
                ('image_size_kb', models.IntegerField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, default='', max_length=200)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('taxon_id', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('top_predictions', models.JSONField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('entropy_score', models.FloatField(blank=True, null=True)),
                ('identification_status', models.CharField(choices=[('reliable', 'Confident'), ('caution', 'Needs confirmation'), ('unreliable', 'Not confident'), ('not_an_insect', 'No insect detected')], db_index=True, max_length=30)),
                ('pest_status', models.CharField(choices=[('unknown', 'Unknown - not assessed'), ('pest', 'Known pest'), ('beneficial', 'Beneficial insect'), ('neutral', 'Neutral')], default='unknown', max_length=20)),
                ('provider', models.CharField(default='insect.id', max_length=30)),
                ('model_version', models.CharField(blank=True, default='', max_length=60)),
                ('farmer_confirmed', models.BooleanField(blank=True, null=True)),
                ('correct_identification', models.CharField(blank=True, default='', max_length=200)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insect_identifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='detection_i_timesta_fd1d9d_idx'), models.Index(fields=['identification_status', '-timestamp'], name='detection_i_identif_2413c2_idx')],
            },
        ),
    ]
