# Generated by Django 4.2.17 on 2026-10-06 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_insectidentificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisconversation',
            name='insect_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='detection.insectidentificationlog'),
        ),
        migrations.AlterField(
            model_name='diagnosisconversation',
            name='diagnosis_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='detection.diagnosislog'),
        ),
        migrations.AddIndex(
            model_name='diagnosisconversation',
            index=models.Index(fields=['insect_log', '-created_at'], name='detection_d_insect__800a4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosisconversation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('diagnosis_log__isnull', False), ('insect_log__isnull', True)), models.Q(('diagnosis_log__isnull', True), ('insect_log__isnull', False)), _connector='OR'), name='conversation_has_exactly_one_subject'),
        ),
    ]
