# Generated by Django 6.1.1 on 2026-09-10 02:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetricsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_packets_sent', models.PositiveIntegerField(default=0)),
                ('total_packets_received', models.PositiveIntegerField(default=0)),
                ('avg_alert_latency_sec', models.FloatField(blank=True, null=True)),
                ('alerts_under_2min_pct', models.FloatField(blank=True, help_text='% of alerts delivered within 2 minutes', null=True)),
                ('water_usage_manual_l', models.FloatField(blank=True, help_text='Baseline manual irrigation litres', null=True)),
                ('water_usage_ai_l', models.FloatField(blank=True, help_text='AI-controlled irrigation litres', null=True)),
                ('server_uptime_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('crop_pred_accuracy_pct', models.FloatField(blank=True, help_text='k-fold validated accuracy for the day', null=True)),
                ('sus_score', models.FloatField(blank=True, help_text='System Usability Scale 0-100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sus_respondents', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metrics Log',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. North Plot, Field-3', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('current_crop', models.CharField(blank=True, max_length=100)),
                ('lifecycle_stage', models.CharField(choices=[('pre_sowing', 'Pre-Sowing'), ('sowing', 'Sowing'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting / Grain Fill'), ('maturity', 'Maturity'), ('harvest', 'Harvest'), ('fallow', 'Fallow')], default='fallow', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique hardware ID burned into firmware', max_length=64, unique=True)),
                ('hardware_type', models.CharField(choices=[('raspberry_pi', 'Raspberry Pi'), ('arduino_uno', 'Arduino Uno'), ('arduino_micro', 'Arduino Micro'), ('esp32', 'ESP32'), ('custom', 'Custom')], default='esp32', max_length=20)),
                ('connectivity', models.CharField(choices=[('gsm', 'GSM / 4G'), ('wifi', 'Wi-Fi'), ('ethernet', 'Ethernet'), ('bluetooth', 'Bluetooth'), ('mqtt', 'MQTT over Wi-Fi')], default='gsm', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('placement_zone', models.CharField(blank=True, help_text='Zone label from K-medoids clustering, e.g. Z1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tampered', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=30)),
                ('has_solar_power', models.BooleanField(default=False, help_text='Solar-based power storage unit present')),
                ('battery_pct', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='iot_sensor.field')),
            ],
            options={
                'ordering': ['field', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('soil_moisture_pct', models.FloatField(blank=True, help_text='Soil moisture %', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nitrogen_ppm', models.FloatField(blank=True, help_text='N — ppm', null=True)),
                ('phosphorus_ppm', models.FloatField(blank=True, help_text='P — ppm', null=True)),
                ('potassium_ppm', models.FloatField(blank=True, help_text='K — ppm', null=True)),
                ('soil_ph', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('temperature_c', models.FloatField(blank=True, help_text='°C', null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wind_speed_kmh', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('solar_lux', models.FloatField(blank=True, help_text='Solar luminous intensity (lux)', null=True)),
                ('rainfall_mm', models.FloatField(blank=True, help_text='mm in last interval', null=True)),
                ('water_level_pct', models.FloatField(blank=True, help_text='Tank/reservoir water level %', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('packet_id', models.CharField(blank=True, max_length=64)),
                ('rssi_dbm', models.SmallIntegerField(blank=True, help_text='GSM/Wi-Fi signal strength dBm', null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='False if sensor payload failed signature check')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='iot_sensor.field')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot_sensor.sensornode')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai_auto', 'AI Automatic (threshold breach)'), ('manual', 'Manual (farmer override)'), ('schedule', 'Scheduled irrigation')], default='ai_auto', max_length=10)),
                ('valve_open', models.BooleanField(help_text='True = open valve (irrigate)')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, help_text='How long to keep valve open')),
                ('water_volume_l', models.FloatField(blank=True, help_text='Estimated litres to dispense', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to device'), ('acknowledged', 'Acknowledged by device'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_commands', to='iot_sensor.field')),
                ('issued_by', models.ForeignKey(blank=True, help_text='Null = AI-issued', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_commands', to='iot_sensor.sensornode')),
                ('trigger_reading', models.ForeignKey(blank=True, help_text='Reading that triggered this command', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_sensor.sensorreading')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CropPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top3_crops', models.JSONField(default=list, help_text='Top-3 [{crop, confidence}]')),
                ('model_version', models.CharField(default='sklearn_v1', max_length=30)),
                ('farmer_agreed', models.BooleanField(blank=True, null=True)),
                ('actual_crop_grown', models.CharField(blank=True, max_length=100)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_predictions', to='iot_sensor.field')),
                ('reading', models.ForeignKey(blank=True, help_text='Sensor reading used as input', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_sensor.sensorreading')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(choices=[('soil_moisture_pct', 'Soil Moisture (%)'), ('nitrogen_ppm', 'Nitrogen (ppm)'), ('phosphorus_ppm', 'Phosphorus (ppm)'), ('potassium_ppm', 'Potassium (ppm)'), ('soil_ph', 'Soil pH'), ('temperature_c', 'Temperature (°C)'), ('humidity_pct', 'Humidity (%)'), ('wind_speed_kmh', 'Wind Speed (km/h)'), ('solar_lux', 'Solar Luminous Intensity (lux)'), ('water_level_pct', 'Water Level (%)')], max_length=30)),
                ('min_value', models.FloatField(blank=True, help_text='Alert if reading drops below', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Alert if reading exceeds', null=True)),
                ('auto_irrigate_on_low_moisture', models.BooleanField(default=False, help_text='Automatically issue irrigation command when soil moisture drops below min')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='iot_sensor.field')),
            ],
            options={
                'ordering': ['field', 'variable'],
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('variable', models.CharField(max_length=30)),
                ('actual_value', models.FloatField()),
                ('breach_type', models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=5)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reading_time', models.DateTimeField(help_text='When sensor took the reading')),
                ('alert_created', models.DateTimeField(auto_now_add=True, help_text='When alert was created in DB')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot_sensor.field')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_sensor.sensorreading')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_sensor.sensorthreshold')),
            ],
            options={
                'ordering': ['-alert_created'],
            },
        ),
        migrations.CreateModel(
            name='FieldZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_label', models.CharField(help_text='e.g. Z1, Z2, Z3', max_length=20)),
                ('centroid_lat', models.DecimalField(blank=True, decimal_places=7, help_text='K-medoid centroid latitude', max_digits=10, null=True)),
                ('centroid_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('valve_lat', models.DecimalField(blank=True, decimal_places=7, help_text="Optimal valve placement (Weiszfeld's algorithm)", max_digits=10, null=True)),
                ('valve_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='iot_sensor.field')),
            ],
            options={
                'ordering': ['field', 'zone_label'],
                'unique_together': {('field', 'zone_label')},
            },
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['field', '-recorded_at'], name='iot_sensor__field_i_d8730a_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['node', '-recorded_at'], name='iot_sensor__node_id_3d4371_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorthreshold',
            unique_together={('field', 'variable')},
        ),
        migrations.AddIndex(
            model_name='sensoralert',
            index=models.Index(fields=['field', 'is_read'], name='iot_sensor__field_i_39ffc4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralert',
            index=models.Index(fields=['-alert_created'], name='iot_sensor__alert_c_c01e9b_idx'),
        ),
    ]
