# Generated by Django 4.2.17 on 2026-10-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated. Flash this into the device firmware; it is sent as the X-Device-Key header.', max_length=64, unique=True),
        ),
    ]
