# Generated by Django 4.2.17 on 2026-10-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrolease', '0007_agroprofile_rejection_reason_and_more'),
        ('iot_sensor', '0002_sensornode_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='land',
            field=models.ForeignKey(blank=True, help_text='The leased/owned land parcel this monitored field corresponds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_fields', to='agrolease.land'),
        ),
    ]
