# Generated by Django 4.2.17 on 2026-09-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('soil_type', models.CharField(max_length=100)),
                ('water_source', models.CharField(max_length=100)),
                ('suitable_crops', models.CharField(max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_frequency', models.CharField(default='per season', max_length=50)),
                ('duration_months', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending_approval', 'Pending Admin Approval'), ('leased', 'Leased')], default='pending_approval', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='land_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_requests', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='agrolease.land')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_text', models.TextField()),
                ('signed_by_owner', models.BooleanField(default=False)),
                ('signed_by_farmer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agrolease.leaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='AgroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Land Owner'), ('farmer', 'Farmer'), ('admin', 'Admin')], default='farmer', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agroprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
