# Generated by Django 4.2.17 on 2026-10-05 20:13

from django.db import migrations, models


def backfill_verification_status(apps, schema_editor):
    """
    Existing rows all default to 'unsubmitted'. Profiles that are already
    verified must read 'approved', and profiles that uploaded documents but were
    never approved must read 'pending', so the admin queue is accurate on day
    one rather than showing every verified owner as not submitted.
    """
    AgroProfile = apps.get_model('agrolease', 'AgroProfile')
    AgroProfile.objects.filter(is_verified=True).update(verification_status='approved')
    AgroProfile.objects.filter(
        is_verified=False, verification_submitted_at__isnull=False,
    ).update(verification_status='pending')


def noop_reverse(apps, schema_editor):
    """Nothing to undo: the columns themselves are dropped by the reverse of AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ('agrolease', '0006_lease_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='agroprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Shown to the user when verification is rejected.'),
        ),
        migrations.AddField(
            model_name='agroprofile',
            name='verification_status',
            field=models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Submitted - awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='unsubmitted', max_length=20),
        ),
        migrations.RunPython(backfill_verification_status, noop_reverse),
    ]
